import {Figtree} from 'next/font/google'
import Sidebar from "@/widgets/sidebar/ui";
import {Providers} from "@/app/providers";
import getSongsByUserId from "@/action/getSongsByUserId";
import Player from "@/app/features/player/ui";

const font = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const revalidate = 0;
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const userSongs = await getSongsByUserId()
  return (
    <html lang="en">
      <body  style={{margin:0}} className={font.className}>
      <Providers>
          <Sidebar songs={userSongs}>
              {children}
          </Sidebar>
          <Player/>
      </Providers>
      </body>
    </html>
  )
}
