import { Inter } from 'next/font/google'
import Sidebar from "@/widgets/sidebar/ui";
import {Providers} from "@/app/providers";

const inter = Inter({ subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body  style={{margin:0}} className={inter.className}>
      <Providers>
          <Sidebar>
              {children}
          </Sidebar>
      </Providers>
      </body>
    </html>
  )
}
